# Generated by Django 3.2.2 on 2021-07-18 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainbuild', '0013_auto_20210718_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildStageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stage_name', models.CharField(max_length=150)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('stage_startdate', models.DateTimeField(blank=True, null=True)),
                ('stage_enddate', models.DateTimeField(blank=True, null=True)),
                ('build_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbuild.mybuild')),
                ('stage_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildstages.buildstageelement')),
            ],
        ),
    ]
