# Generated by Django 3.2.2 on 2021-07-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0013_auto_20210718_1741'),
        ('buildstages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildstage',
            name='build_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbuild.mybuild'),
        ),
    ]
