# Generated by Django 3.2.2 on 2021-08-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0002_alter_buildstage_build_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildstage',
            name='stage_element',
        ),
        migrations.AddField(
            model_name='buildstageelement',
            name='stage_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildstages.buildstage'),
        ),
    ]
