# Generated by Django 3.2.2 on 2021-08-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0003_auto_20210801_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildstageelement',
            old_name='stage_element',
            new_name='stage',
        ),
    ]
