# Generated by Django 3.2.2 on 2021-08-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0013_auto_20210718_1741'),
        ('buildstages', '0004_rename_stage_element_buildstageelement_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildstageelement',
            name='build_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbuild.mybuild'),
        ),
    ]
