# Generated by Django 3.2.2 on 2021-08-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0005_buildstageelement_build_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildstageelement',
            name='build_id',
        ),
    ]
