# Generated by Django 3.2.2 on 2021-08-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0006_remove_buildstageelement_build_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildstageelement',
            name='stage',
        ),
        migrations.AddField(
            model_name='buildstage',
            name='stage_elements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildstages.buildstageelement'),
        ),
    ]
