# Generated by Django 3.2.2 on 2021-08-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0007_auto_20210801_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildstage',
            name='stage_elements',
        ),
        migrations.AddField(
            model_name='buildstageelement',
            name='stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildstages.buildstage'),
        ),
    ]
