# Generated by Django 3.2.2 on 2021-08-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0008_auto_20210801_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildstageelement',
            name='stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='buildstages.buildstage'),
        ),
    ]
