# Generated by Django 3.2.2 on 2021-08-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0010_alter_buildstageelement_stage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildstageelement',
            old_name='stage_id',
            new_name='buildstage',
        ),
        migrations.AlterOrderWithRespectTo(
            name='buildstageelement',
            order_with_respect_to='buildstage',
        ),
    ]
