# Generated by Django 3.2.2 on 2021-08-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0011_auto_20210806_2138'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='buildstageelement',
            order_with_respect_to=None,
        ),
    ]
