# Generated by Django 3.2.2 on 2021-08-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0012_alter_buildstageelement_order_with_respect_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageElements',
            fields=[
                ('buildstage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buildstages.buildstage')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            bases=('buildstages.buildstage',),
        ),
    ]
