# Generated by Django 3.2.2 on 2021-08-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0013_stageelements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StageElements',
        ),
    ]
