# Generated by Django 3.2.2 on 2021-08-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0014_delete_stageelements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildstageelement',
            name='buildstage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='buildstages.buildstage'),
        ),
    ]
