# Generated by Django 3.2.2 on 2021-08-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0015_alter_buildstageelement_buildstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildstage',
            name='stage_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
