# Generated by Django 3.2.2 on 2021-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0016_buildstage_stage_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildstage',
            name='stage_budget_calculation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buildstage',
            name='budget',
            field=models.FloatField(blank=True, null=True, verbose_name='Zakładany budżet'),
        ),
        migrations.AlterField(
            model_name='buildstage',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Etap zakończony'),
        ),
        migrations.AlterField(
            model_name='buildstage',
            name='stage_enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia etapu'),
        ),
        migrations.AlterField(
            model_name='buildstage',
            name='stage_name',
            field=models.CharField(max_length=150, verbose_name='Nazwa etapu'),
        ),
        migrations.AlterField(
            model_name='buildstage',
            name='stage_startdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczecia etapu'),
        ),
    ]
