# Generated by Django 3.2.2 on 2021-08-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildstages', '0017_auto_20210820_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildstage',
            name='stage_enddate',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia etapu'),
        ),
        migrations.AlterField(
            model_name='buildstage',
            name='stage_startdate',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozpoczecia etapu'),
        ),
    ]
