# Generated by Django 3.2.2 on 2021-05-29 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBuildDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Budynek Jednorodzinny', 'Budynek Jednorodzinny'), ('Budynek Wielorodzinny', 'Budynek Wielorodzinny'), ('Garaż', 'Garaż'), ('Inny', 'Inny')], max_length=50)),
                ('province', models.CharField(choices=[('Dolnośląskie', 'Dolnośląskie'), ('Kujawsko-Pomorskie', 'Kujawsko-Pomorskie'), ('Lubelskie', 'Lubelskie'), ('Lubuskie', 'Lubuskie'), ('Łódzkie', 'Łódzkie'), ('Małopolskie', 'Małopolskie'), ('Mazowieckie', 'Mazowieckie'), ('Opolskie', 'Opolskie'), ('Podkarpackie', 'Podkarpackie'), ('Podlaskie', 'Podlaskie'), ('Pomorskie', 'Pomorskie'), ('Śląskie', 'Śląskie'), ('Świętokrzyskie', 'Świętokrzyskie'), ('Warmińsko-Mazurskie', 'Warmińsko-Mazurskie'), ('Wielkopolskie', 'Wielkopolskie'), ('Zachodniopomorskie', 'Zachodniopomorskie')], max_length=20)),
                ('descriptions', models.TextField(blank=True)),
                ('country', models.CharField(choices=[('Polska', 'Polska')], default='Polska', max_length=15)),
                ('location', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Pozwolenia/Papierologia', 'Pozwolenia/Papierologia'), ('Przygotowanie działki', 'Przygotowanie działki'), ('Poziom 0', 'Poziom 0'), ('Instalacje', 'Instalacje'), ('Ściany', 'Ściany'), ('Strop', 'Strop'), ('Dach', 'Dach')], max_length=25)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('service', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/img_build/%Y/%m%d')),
                ('done', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
