# Generated by Django 3.2.2 on 2021-05-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybuild',
            name='done',
        ),
    ]
