# Generated by Django 3.2.2 on 2021-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0002_remove_mybuild_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybuild',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa Budowy'),
        ),
    ]
