# Generated by Django 3.2.2 on 2021-06-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0004_mybuild_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybuilddescription',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbuild.mybuild'),
        ),
        migrations.AlterField(
            model_name='mybuild',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/img_build/%Y/%m%d', verbose_name='Poglądowe zdjęcie budowy'),
        ),
    ]
