# Generated by Django 3.2.2 on 2021-07-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0007_alter_mybuilddescription_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stages', models.CharField(max_length=150)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainbuild.mybuild')),
            ],
        ),
    ]
