# Generated by Django 3.2.2 on 2021-07-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0008_buildstages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stage_name', models.CharField(max_length=150)),
                ('budget', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('build_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainbuild.mybuild')),
            ],
        ),
        migrations.CreateModel(
            name='BuildStageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buildstages',
            name='name',
        ),
        migrations.DeleteModel(
            name='Stage1',
        ),
        migrations.DeleteModel(
            name='BuildStages',
        ),
        migrations.AddField(
            model_name='buildstage',
            name='stage_element',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbuild.buildstageelement'),
        ),
    ]
