# Generated by Django 3.2.2 on 2021-07-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0009_auto_20210713_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildstage',
            name='build_name',
        ),
        migrations.AddField(
            model_name='buildstage',
            name='build_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbuild.mybuild'),
        ),
    ]
