# Generated by Django 3.2.2 on 2021-07-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0010_auto_20210718_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildstage',
            name='stage_enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildstage',
            name='stage_startdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
