# Generated by Django 3.2.2 on 2021-07-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0011_auto_20210718_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildstage',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildstage',
            name='stage_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainbuild.buildstageelement'),
        ),
    ]
