# Generated by Django 3.2.2 on 2021-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0015_alter_mybuild_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybuild',
            name='image',
            field=models.ImageField(blank=True, default='assets/img/home-logo.jpg', null=True, upload_to='%Y/%m%d', verbose_name='Poglądowe zdjęcie budowy'),
        ),
    ]
