# Generated by Django 3.2.2 on 2021-08-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0018_alter_mybuild_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybuild',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Zakładany koszt budowy'),
        ),
        migrations.AddField(
            model_name='mybuild',
            name='build_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rzeczywisty koszt budowy'),
        ),
    ]
