# Generated by Django 3.2.2 on 2021-08-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainbuild', '0020_mybuild_budget_calculation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sso',
        ),
    ]
